export const NODES = [
  {
    id: "ice-airports",
    title: "ICE Airport Deployment",
    description: "Conservative commentary on ICE agents at airports during TSA shutdown. Tribal epistemology used by both sides to avoid structural accountability.",
    tribe: "RIGHT",
    date: "2019-01-15",
    source: "Fox News / Conservative Media",
    url: "https://www.foxnews.com",
    manipulation: ["AFAFF", "MOTIVE"],
    biblical: ["IMAGO", "GER"],
    plumb: { process: 2, locus: 2, uplift: 1, means: 2, blueprint: 2 },
    verdict: "Both sides deployed real grievances to evade structural responsibility.",
  },
  {
    id: "dhs-shutdown",
    title: "DHS Shutdown Debate",
    description: "Right-wing commentary on partial DHS funding shutdown. Civilisational urgency deployed to bypass scrutiny of Republican procedural consistency.",
    tribe: "RIGHT",
    date: "2018-12-22",
    source: "National Review",
    url: "https://www.nationalreview.com",
    manipulation: ["AFAFF", "URGENCY", "MOTIVE"],
    biblical: ["PROPHETIC", "STRUCTURAL"],
    plumb: { process: 2, locus: 1, uplift: 2, means: 2, blueprint: 1 },
    verdict: "Accurate diagnosis of Democrat overreach; silent on Republican blocking of standalone TSA bills.",
  },
  {
    id: "estate-tax",
    title: "NY Estate Tax Proposal",
    description: "NY mayoral candidate's estate tax proposal debated. Both the proposal and its critics avoid the structural question: why do modest homes cost estate-tax-level money?",
    tribe: "RIGHT",
    date: "2021-05-10",
    source: "NY Post",
    url: "https://nypost.com",
    manipulation: ["SCALE", "MOTIVE"],
    biblical: ["JUBILEE", "STRUCTURAL"],
    plumb: { process: 3, locus: 1, uplift: 2, means: 2, blueprint: 2 },
    verdict: "Debating wealth transfer at death avoids the Jubilee question of why wealth concentrates this way at all.",
  },
  {
    id: "un-veto",
    title: "UN Security Council Veto",
    description: "Video arguing UN veto system was designed by colonial powers to protect economic interests. Strong structural diagnosis, imprecise supporting claims.",
    tribe: "GEOPOLITICS",
    date: "2023-11-15",
    source: "Al Jazeera / Independent",
    url: "https://www.aljazeera.com",
    manipulation: ["AFAFF", "SCALE"],
    biblical: ["PROPHETIC", "STRUCTURAL", "GREAT"],
    plumb: { process: 1, locus: 1, uplift: 1, means: 2, blueprint: 1 },
    verdict: "Structural diagnosis strong. Specific figures embellished. The architecture of empire embedded in post-war institutions.",
  },
  {
    id: "michigan-election",
    title: "Michigan Election Claims",
    description: "Claims about Michigan ballot irregularities. Real voter-roll failures leveraged into broad disenfranchisement framework. Scale elision and asymmetric evidence standards throughout.",
    tribe: "RIGHT",
    date: "2020-11-10",
    source: "Gateway Pundit",
    url: "https://www.thegatewaypundit.com",
    manipulation: ["AFAFF", "ASYM", "CATEGORY"],
    biblical: ["PROPHETIC", "LIBERTY"],
    plumb: { process: 2, locus: 1, uplift: 1, means: 2, blueprint: 1 },
    verdict: "Real systemic failures used to build an access-restriction architecture that harms the voters it claims to protect.",
  },
  {
    id: "christian-nationalism",
    title: "UK Christian Nationalism",
    description: "UK speaker advocating blasphemy laws, mandatory Christianity, inquisition to purge heretics. Classic church-state fusion — the prophetic warning made visible.",
    tribe: "RELIGION",
    date: "2024-02-20",
    source: "Reformed Forum / UK Speaker",
    url: "https://reformedforum.org",
    manipulation: ["FLUENCY", "URGENCY"],
    biblical: ["LIBERTY", "GREAT", "PROPHETIC"],
    plumb: { process: 1, locus: 2, uplift: 1, means: 1, blueprint: 1 },
    verdict: "The Revelation 13 architecture in a British accent. Power-seeking through legal coercion is not the kingdom; it is its counterfeit.",
  },
  {
    id: "iran-operation",
    title: "Operation Epic Fury",
    description: "Analysis of US military strikes on Iran. Strong financial analysis, no moral floor. AI integrated into lethal targeting. Anthropic penalised for maintaining ethical constraints.",
    tribe: "GEOPOLITICS",
    date: "2024-01-05",
    source: "Defense Analysis",
    url: "https://www.defense.gov",
    manipulation: ["MOTIVE", "SCALE", "URGENCY"],
    biblical: ["PROPHETIC", "GREAT", "STRUCTURAL"],
    plumb: { process: 1, locus: 1, uplift: 1, means: 1, blueprint: 1 },
    verdict: "Digital and physical warfare domains merging. The successor question: what precedent does this leave for the next administration?",
  },
  {
    id: "liberal-hypocrisy",
    title: "Democratic Tax Policy",
    description: "Commentary on Democratic internal tensions and California/NY tax policy. Real data on revenue concentration among top earners weaponised to resist structural redistribution.",
    tribe: "RIGHT",
    date: "2022-03-15",
    source: "Wall Street Journal / Editorial",
    url: "https://www.wsj.com",
    manipulation: ["AFAFF", "CATEGORY", "MOTIVE"],
    biblical: ["JUBILEE", "STRUCTURAL", "PROPHETIC"],
    plumb: { process: 3, locus: 1, uplift: 2, means: 3, blueprint: 2 },
    verdict: "Productivity conflated with compensation. The framework protects concentration while appearing to defend the entrepreneurial class.",
  },
  {
    id: "wes-huff",
    title: "Wes Huff / State of Dead",
    description: "Wes Huff's apologetics interview missed soul sleep, annihilationism, and Great Controversy framework on the problem of evil. Platonic immortality embedded in mainstream Christian assumptions.",
    tribe: "RELIGION",
    date: "2023-09-12",
    source: "Apologetics Canada",
    url: "https://www.apologeticscanada.com",
    manipulation: ["FLUENCY"],
    biblical: ["PROPHETIC", "GREAT"],
    plumb: { process: 4, locus: 3, uplift: 3, means: 3, blueprint: 3 },
    verdict: "Fluent in defending Christianity; insufficient on state of the dead. The Lazarus argument closes the case biblically.",
  },
  {
    id: "british-identity",
    title: "British Identity Debate",
    description: "Birbalsingh vs Tomlinson on national identity. Tomlinson conflates heritage with lineage, commits gender analogy fallacy. Birbalsingh's school outcomes challenge his premise.",
    tribe: "RIGHT",
    date: "2023-10-22",
    source: "UnHerd / UK Media",
    url: "https://unherd.com",
    manipulation: ["AFAFF", "CATEGORY"],
    biblical: ["GER", "IMAGO", "PROPHETIC"],
    plumb: { process: 3, locus: 2, uplift: 1, means: 2, blueprint: 2 },
    verdict: "Covenant, not genealogy, is the biblical criterion. Ruth, the Exodus mixed multitude, Isaiah 56.",
  },
  {
    id: "voter-fraud",
    title: "Voter Registration Fraud",
    description: "Undercover footage of petition fraud. Central self-refutation: San Francisco footage showed fraud by billionaire-backed operatives opposing wealth tax — contradicting the video's own premise.",
    tribe: "RIGHT",
    date: "2024-05-20",
    source: "Project Veritas / Alternative Media",
    url: "https://www.projectveritas.com",
    manipulation: ["AFAFF", "MOTIVE", "SCALE"],
    biblical: ["PROPHETIC", "IMAGO"],
    plumb: { process: 2, locus: 1, uplift: 1, means: 2, blueprint: 1 },
    verdict: "The most dangerous manipulation uses evidence that disproves its own conclusion. The system protects those whose fraud wasn't named.",
  },
  {
    id: "ndtv-violence",
    title: "Neil deGrasse Tyson on Violence",
    description: "Tyson correctly identifies violence as internal to human nature, then spends the rest blaming the containers. Conversation and coexistence require a theological foundation science cannot generate.",
    tribe: "GEOPOLITICS",
    date: "2022-08-15",
    source: "StarTalk / Social Media",
    url: "https://www.startalkradio.net",
    manipulation: ["AFAFF", "SCALE"],
    biblical: ["IMAGO", "STRUCTURAL", "PROPHETIC"],
    plumb: { process: 3, locus: 3, uplift: 3, means: 2, blueprint: 3 },
    verdict: "The older diagnosis is what Scripture calls sin. The solution Tyson cannot reach from where he's standing is the image of God.",
  },
  {
    id: "pa-terrorism",
    title: "PA Terrorism / Immigration Framing",
    description: "Pennsylvania ISIS-inspired attack by American citizens framed as mass-migration problem. Both suspects are US-born suburban citizens — the mass-migration framing is self-refuted by the commentator's own facts.",
    tribe: "RIGHT",
    date: "2024-10-02",
    source: "Local Media / Conservative Framing",
    url: "https://www.pennlive.com",
    manipulation: ["AFAFF", "CATEGORY", "MOTIVE"],
    biblical: ["GER", "IMAGO", "PROPHETIC"],
    plumb: { process: 2, locus: 1, uplift: 1, means: 2, blueprint: 1 },
    verdict: "Category error: ISIS is theocratic, not left-wing. The framing protects a policy conclusion the evidence cannot support.",
  },
];
